jobs:
- name: job-build-app
  public: true
  serial: true
  plan:
  - get: git-concourse-shell-script
    trigger: true
  - task: run-build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: git-concourse-shell-script
      run:
        path: bash
        args: [./git-concourse-shell-script/my-task/task.sh]

resources:
  - name: git-concourse-shell-script
    type: git
    source:
      uri: https://github.com/brawlerkrishna/concourse-shell-script.git
      branch: master



